#!/usr/bin/env bash
# This script installs nginx and configures it

sudo apt-get -y update
sudo apt-get install nginx
ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
service nginx restart
