#!/usr/bin/env bash
# This scrpt configures a new ubuntu server's rediect file to  a custom404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sh -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"
new_config="server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
	add_header X-Served-By $HOSTNAME;

	location / {
		try_files \$uri \$uri/ =404;
	}
	error_page 404 /404.html;
	location /404.html {
		internal;
	}

	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"
sudo sh -c "echo '$new_config' > /etc/nginx/sites-enabled/default"
if [ "$(pgrep nginx)" -le 0 ]:
then
    service nginx start
else
    service nginx restart
fi;
