#!/usr/bin/env bash
# This script fixes the connection issue to port 80 refactored
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
