#!/usr/bin/env bash
# This scripts prints content of the file /etc/passwd
while read -r username password uid gid info home cmd
do
    echo "The user $username is part of the $gid, lives in $home and rides $cmd. $uid place is protected by the passcode $password, more info about the user here: $info"
done < "/etc/passwd"
