#!/usr/bin/env bash
# This scripts prints numbers from 1 - 20 and some superstitions
iv='bad luck from China'
ix='bad luck from Japan'
sept='bad luck from Italy'
i="1"
while (("$i" != "21"))
do
    echo "$i"
    case $i in
      "4") echo "$iv";;
      "9") echo "$ix";;
      "17") echo "$sept";;
    esac
    i=$((i + 1))
done
