#!/usr/bin/env bash
# This scripts dis[plays time for 10 minutes
hr="0"
while (("$hr" < "13"))
do
    echo "Hour: $hr"
    min="1"
    while (("$min" < "60"))
    do
        echo "$min"
	min=$((min + 1))
    done
    hr=$((hr + 1))
done
