#!/usr/bin/env bash
# get root priviledges
sudo su
sudo apt-get update -y
sudo apt upgrade -y
# Install ufw
sudo apt install ufw
# block all incoming signals
sudo ufw default deny incoming -y
# allow all outgoing signals
sudo ufw default allow outgoing -y
# Allow port 22, 443, 80
sudo ufw allow ssh
sudo ufw allow http
sudo allow https

sudo ufw enable
sudo ufw status numbered
