#!/usr/bin/env bash
# A bash script that configures an ubuntu server to
# - Resolve localhost to 127.0.0.2
# - Resolves facebook.com to 8.8.8.8

echo "127.0.0.2		localhost" >> /etc/hosts
echo "8.8.8.8		facebook.com" >> /etc/hosts
